Assignments 3 and 4
isa-ulisboa/greends-ipython pull request #32
Opened 2022-10-13 16:51 UTC by luisgcms

2022-10-13 17:02 UTC, luisgcms reviewed
File commenting update

2022-10-13 17:07 UTC, joaopalma requested changes

2022-10-13 17:07 UTC, joaopalma commented on FORGE/LUISSOARES/field_capacity.py
> +    C - Percentage of clay; S - Percentage of silt; OM - Percentage of organic matter; D - Bulk density; topsoil - qualitative variable
its a good try... :)
but try this:
install the extension autodocstring in VSCode and type """ again

2022-10-14 15:38 UTC, luisgcms reviewed
Commentary update with autoDocstring

2022-10-15 07:41 UTC, merged